import labels from '../assets/labels/English.labels';

export const stepsData = [
  {
    id: 1,
    step: '01',
    label: labels.describeYourPlace,
    selected: true,
    completed: false,
  },
  {
    id: 2,
    step: '02',
    label: labels.roomRent,
    selected: false,
    completed: false,
  },
  {
    id: 3,
    step: '03',
    label: labels.guests,
    selected: false,
    completed: false,
  },
  {
    id: 4,
    step: '04',
    label: labels.placeLocated,
    selected: false,
    completed: false,
  },
  {
    id: 5,
    step: '05',
    label: labels.basicsAboutYourPlace,
    selected: false,
    completed: false,
  },
  {
    id: 6,
    step: '06',
    label: labels.specifications,
    selected: false,
    completed: false,
  },
  {
    id: 7,
    step: '07',
    label: labels.price,
    selected: false,
    completed: false,
  },
  {
    id: 8,
    step: '08',
    label: labels.addDiscounts,
    selected: false,
    completed: false,
  },
  {
    id: 9,
    step: '09',
    label: labels.preview,
    selected: false,
    completed: false,
  },
  {
    id: 10,
    step: '10',
    label: labels.agreement,
    selected: false,
    completed: false,
  },
];
export const myCarsStepsData = [
  {
    id: 1,
    step: '01',
    label: labels.basicInfo,
    selected: true,
    completed: false,
  },
  {
    id: 2,
    step: '02',
    label: labels.location,
    selected: false,
    completed: false,
  },
  {
    id: 3,
    step: '03',
    label: labels.specifications,
    selected: false,
    completed: false,
  },
  {
    id: 4,
    step: '04',
    label: labels.features,
    selected: false,
    completed: false,
  },
  {
    id: 5,
    step: '05',
    label: labels.pricing,
    selected: false,
    completed: false,
  },
  {
    id: 6,
    step: '06',
    label: labels.addDiscounts,
    selected: false,
    completed: false,
  },
  {
    id: 7,
    step: '07',
    label: labels.uploadPhoto,
    selected: false,
    completed: false,
  },
  {
    id: 8,
    step: '08',
    label: labels.preview,
    selected: false,
    completed: false,
  },
];
